[mgr]
prepend_keymap = [
	{ on = [ "<C-n>" ], run = '''
	    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
	''' },
	{ on = [ "g", "n" ], run = "cd /var/mnt/nisu" },
	{ on = "f", run = "plugin jump-to-char" }
]
